// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Ojo: esta url la usa SOLO el CLI (migrate, studio, seed), no la app.
    // Las migraciones no funcionan a traves del pooler de Neon, asi que aca va
    // la conexion directa (DIRECT_URL). La app en cambio usa DATABASE_URL, que
    // en produccion es la connection string con `-pooler`. Ver lib/prisma.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
